"""Stage: ocr_frames_local. Local OCR via the internal local-ai service.

Phase D drop-in replacement for ``analyze_frames`` (GPT-4o Vision) when
``settings.ocr_provider == "local"``.

Privacy contract:
- Only the storage **keys** (``sessions/<uuid>/frames/frame_NNNN.jpg``)
  are sent to local-ai. No image bytes ever cross the boundary.
- The full per-frame OCR text is written to the artifact file as
  ``"analyze_frames"`` (same key the legacy stage uses), so
  ``build_timeline`` and downstream stages remain transparent.
- The summary stored in ``pipeline_artifacts["analyze_frames"]`` carries
  ``ocr_text`` and ``ui_summary`` per frame (same shape the legacy stage
  publishes). Phase E will scrub this further; for now the public-artifact
  scrubber from Phase A already strips ``ocr_text`` from API responses.
- ``ui_summary`` is generated by a deterministic local heuristic — NO LLM
  call. GPT-4o Vision is bypassed entirely.

Per-frame artifact item shape (matches legacy ``analyze_frames``):
    {
        "idx": 7,
        "t": 12.34,
        "key": "sessions/<id>/frames/frame_0007.jpg",
        "ocr_text": "...",
        "ui_summary": "UI text: ...",
        "ocr": {                          # extra: raw OCR detail (Phase D)
            "engine": "tesseract",
            "model": "tesseract",
            "language": "eng+ita",
            "blocks": [{"text": ..., "confidence": ..., "bbox": {...}}]
        }
    }
"""
from __future__ import annotations

import logging

from sqlalchemy.ext.asyncio import AsyncSession

from app.ai.local_client import LocalAIClient, LocalAIError
from app.ai.local_models import OCRFrameResult
from app.config import settings
from app.models.session import Session
from app.pipeline import common

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# UI-summary heuristic (deterministic, local, no LLM)
# ---------------------------------------------------------------------------


def _ui_summary_from_ocr_text(text: str, max_chars: int = 120) -> str:
    """Cheap local heuristic so the timeline has *some* per-frame caption.

    Phase E may revisit this. For now we just publish a short, sanitized
    preview of the recognized text. This is intentionally NOT a model call.
    """
    if not text or not text.strip():
        return "Frame with no recognized UI text."
    one_line = " ".join(text.split())
    if len(one_line) > max_chars:
        one_line = one_line[: max_chars - 1].rstrip() + "…"
    return f"UI text: {one_line}"


# ---------------------------------------------------------------------------
# Stage entry point
# ---------------------------------------------------------------------------


async def run(db: AsyncSession, session: Session) -> None:
    # Idempotent: legacy and local both publish under "analyze_frames".
    if common.stage_done(session, "analyze_frames"):
        return

    frames = (session.pipeline_artifacts or {}).get("extract_frames") or []
    if not isinstance(frames, list) or not frames:
        raise RuntimeError(
            "ocr_frames_local requires extract_frames to have produced frames"
        )

    frame_keys: list[str] = [str(f["key"]) for f in frames]
    language = settings.ocr_lang or None

    try:
        async with LocalAIClient(base_url=settings.local_ai_base_url) as client:
            response = await client.ocr(frame_keys=frame_keys, language=language)
    except LocalAIError as exc:
        raise RuntimeError(f"local-ai ocr failed: {exc!s}") from exc

    # Index responses by frame_key so we can match positionally even if the
    # service ever reorders. (Today it preserves order.)
    by_key: dict[str, OCRFrameResult] = {r.frame_key: r for r in response.results}
    if len(by_key) != len(frame_keys):
        raise RuntimeError(
            "local-ai ocr returned a different number of results than requested"
        )

    full_results: list[dict] = []
    summary: list[dict] = []
    engine_seen: str = ""
    model_seen: str = ""

    for f in frames:
        idx = int(f["idx"])
        t = float(f["t"])
        key = str(f["key"])
        r = by_key.get(key)
        if r is None:
            raise RuntimeError("local-ai ocr did not return a result for a requested key")

        engine_seen = r.engine or engine_seen
        model_seen = r.model or model_seen
        ocr_text = r.text or ""
        ui_summary = _ui_summary_from_ocr_text(ocr_text)

        full_results.append(
            {
                "idx": idx,
                "t": t,
                "key": key,
                "ocr_text": ocr_text,
                "ui_summary": ui_summary,
                "ocr": {
                    "engine": r.engine,
                    "model": r.model,
                    "language": r.language,
                    "blocks": [b.model_dump() for b in r.blocks],
                },
            }
        )
        summary.append(
            {
                "idx": idx,
                "t": t,
                "key": key,
                "ocr_text": ocr_text,
                "ui_summary": ui_summary,
            }
        )

    # Write under the legacy key so build_timeline & downstream are transparent.
    common.write_artifact(session.id, "analyze_frames", full_results)
    await common.record_stage(
        db,
        session,
        stage="analyze_frames",
        summary=summary,
        message=f"local OCR analyzed {len(summary)} frames (engine={engine_seen or 'unknown'})",
    )
    await common.add_ai_call(
        db,
        session,
        stage="analyze_frames",
        model=model_seen or engine_seen or "local-ocr",
        input_chars=0,
        output_chars=sum(len(r.get("ocr_text") or "") for r in full_results),
        frame_count=len(full_results),
    )
