"""Deterministic AIProvider for tests (no network calls)."""
from __future__ import annotations

import json
from pathlib import Path

from app.ai.base import (
    AIProvider,
    FrameAnalysis,
    TextResult,
    TranscriptionResult,
    TranscriptSegment,
)


class FakeAIProvider(AIProvider):
    async def transcribe(
        self, audio_path: Path, *, language: str | None = None
    ) -> TranscriptionResult:
        text = "Fake transcript for testing."
        return TranscriptionResult(
            text=text,
            language=language or "en",
            segments=[TranscriptSegment(0.0, 1.0, text)],
            raw={"text": text, "segments": [{"start": 0.0, "end": 1.0, "text": text}]},
            audio_duration_sec=1.0,
            model="fake-stt",
        )

    async def analyze_frame(
        self, image_path: Path, *, prompt: str
    ) -> FrameAnalysis:
        return FrameAnalysis(
            ocr_text=f"OCR of {image_path.name}",
            ui_summary=f"UI summary of {image_path.name}",
            raw={"fake": True},
            input_chars=len(prompt),
            output_chars=32,
            model="fake-vision",
        )

    async def generate_json(self, *, prompt: str) -> TextResult:
        # Build a minimal valid Guide JSON deterministically.
        guide = {
            "schema_version": "1.0",
            "title": "Fake Guide",
            "summary": "Generated by FakeAIProvider for tests.",
            "estimated_duration_minutes": 1.0,
            "prerequisites": [],
            "tools_or_systems": [],
            "steps": [
                {
                    "id": "step-1",
                    "order": 1,
                    "title": "Open application",
                    "description": "Open the application window.",
                    "actions": [{"verb": "open", "target": "application"}],
                    "evidence": {
                        "frame_keys": [],
                        "transcript_excerpt": "",
                        "t_start": 0.0,
                        "t_end": 1.0,
                    },
                    "warnings": [],
                    "notes": [],
                    "confidence": 0.9,
                }
            ],
            "warnings": [],
            "notes": [],
            "troubleshooting": [],
            "metadata": {
                "generated_by": "fake-llm",
                "generated_at": "1970-01-01T00:00:00Z",
                "source_session_id": "",
                "source_duration_sec": None,
            },
        }
        text = json.dumps(guide)
        return TextResult(
            text=text,
            raw={"fake": True},
            input_chars=len(prompt),
            output_chars=len(text),
            model="fake-llm",
        )

