import type { Guide, Session } from "@/lib/types";

interface GuideAboutProps {
    guide: Guide;
    session: Session;
}

function formatDate(iso: string): string {
    try {
        return new Date(iso).toLocaleString(undefined, {
            dateStyle: "medium",
            timeStyle: "short",
        });
    } catch {
        return iso;
    }
}

function formatDuration(seconds: number): string {
    if (seconds < 60) return `${Math.round(seconds)}s`;
    const m = Math.floor(seconds / 60);
    const s = Math.round(seconds % 60);
    return s > 0 ? `${m}m ${s}s` : `${m}m`;
}

export function GuideAbout({ guide, session }: GuideAboutProps) {
    const meta = guide.metadata;

    const rows: { label: string; value: string }[] = [];

    if (meta?.generated_at) {
        rows.push({ label: "Generated at", value: formatDate(meta.generated_at) });
    }
    if (meta?.generated_by) {
        rows.push({ label: "Generated by", value: meta.generated_by });
    }
    const sourceDuration =
        meta?.source_duration_sec ?? session.media_duration_sec;
    if (sourceDuration != null) {
        rows.push({
            label: "Recording duration",
            value: formatDuration(sourceDuration),
        });
    }
    if (meta?.source_session_id) {
        rows.push({ label: "Source session", value: meta.source_session_id });
    }
    if (guide.schema_version) {
        rows.push({ label: "Schema version", value: guide.schema_version });
    }
    if (session.guide_edited_at) {
        rows.push({
            label: "Last edited",
            value: formatDate(session.guide_edited_at),
        });
    }

    if (rows.length === 0) return null;

    return (
        <dl className="grid grid-cols-1 gap-x-6 gap-y-2 text-xs sm:grid-cols-2">
            {rows.map((row) => (
                <div key={row.label} className="flex flex-col gap-0.5">
                    <dt className="font-medium text-muted-foreground">{row.label}</dt>
                    <dd className="font-mono text-foreground">{row.value}</dd>
                </div>
            ))}
        </dl>
    );
}
